# Generated by Django 3.1.5 on 2021-03-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_dashboard', '0003_auto_20210307_2236'),
        ('customer_login', '0002_auto_20210228_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookingdate', models.DateTimeField(auto_now_add=True)),
                ('carbookdate', models.DateField()),
                ('carreturndate', models.DateField()),
                ('totalpayment', models.IntegerField()),
                ('carid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_dashboard.car')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_login.customer')),
            ],
        ),
    ]
