# Generated by Django 3.1.5 on 2021-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
