# Generated by Django 3.1.5 on 2021-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Booking', '0002_booking_total_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='carnumber',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='customername',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='carid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='totalpayment',
            field=models.IntegerField(default=0),
        ),
    ]
