# Generated by Django 3.1.5 on 2021-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_company', models.CharField(max_length=25)),
                ('car_class_type', models.CharField(max_length=20)),
                ('price_per_km', models.IntegerField()),
                ('car_number', models.CharField(max_length=15)),
                ('fuel_type', models.CharField(max_length=10)),
                ('car_description', models.TextField()),
                ('car_availability', models.BooleanField()),
            ],
        ),
    ]
