# Generated by Django 3.1.5 on 2021-03-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0002_auto_20210224_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_km',
            new_name='price_per_day',
        ),
    ]
