# Generated by Django 3.1.5 on 2021-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_username', models.CharField(max_length=20)),
                ('customer_password', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_phone_no', models.CharField(max_length=10)),
                ('customer_aadhar_no', models.CharField(max_length=12)),
                ('customer_address', models.TextField()),
                ('customer_dob', models.DateTimeField()),
            ],
        ),
    ]
