# Generated by Django 3.1.5 on 2021-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0002_auto_20210228_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_dob',
            field=models.DateField(),
        ),
    ]
